### ISSUE TITLE
Option to delete sourcemaps after upload

### ISSUE THREAD

**Issue by valerio** [getsentry/sentry-netlify-build-plugin#40]
I've been using create-react-app to deploy with Netlify and this plugin has been very helpful in setting up the integration. 

The problem I run into is that my sourcemaps get also deployed on Netlify and the full source is visible when opening the inspector.
I'd normally output sourcemaps in a separate directory from the one being deployed, but create-react-app doesn't give me that option without ejecting and having to manage a custom webpack config.

Would an option to delete sourcemaps after deployment be something worth adding to this plugin?
Happy to contribute the change if it's ok.

**Comment by carchrae** [comment]
if you'd like to use my PR (in case it is not merged) you can copy the plugin code into your project (you will need to copy all of the files into `/netlify-plugins/sentry-netlify-build-plugin/` to use the config below)

```toml
[[plugins]]
package = "/netlify-plugins/sentry-netlify-build-plugin/"
   [plugins.inputs]
     sentryDeleteSourceMaps = true
```
i have tested this on my own project and it worked for me.
